import Link from "next/link";
import { cookies } from "next/headers";
import { randomUUID } from "node:crypto";
import { getCurrentUser } from "../../../server/auth";
import { bootstrapAppUserSession } from "../../../server/bootstrap-user";
import { browserEnabled,BROWSER_CLAIM_COOKIE,BROWSER_WORKSPACE_COOKIE,BROWSER_MONTHLY_LIMIT } from "../../../server/marketplace-browser/config";
import { getBrowserClaim,listBrowserWorkspaces,browserScanHistory } from "../../../server/marketplace-browser/repository";
import { BrowserAction,BrowserScanForm } from "../../../components/marketplace-browser/forms";
import { BrowserShell } from "../../../components/marketplace-browser/shell";
export const dynamic="force-dynamic";
export const metadata={title:"Free Website Scanner | AWS Marketplace",description:"Scan public websites in your browser. Set up your free CertScore.ai AWS Marketplace subscription and review evidence-backed reports.",robots:{index:false,follow:false}};
const link="font-semibold text-sky-800 underline underline-offset-4";
const panel="rounded-2xl border border-slate-200 bg-white p-6 sm:p-8";
const date=(value:string|Date)=>new Date(value).toLocaleDateString("en",{year:"numeric",month:"short",day:"numeric",timeZone:"UTC"});
export default async function BrowserMarketplacePage(){
  const enabled=browserEnabled();
  const session=enabled?await getCurrentUser():null;
  const user=session?(await bootstrapAppUserSession(session)).user:null;
  const jar=await cookies();
  const claimToken=jar.get(BROWSER_CLAIM_COOKIE)?.value;
  const claim=enabled&&claimToken?await getBrowserClaim(claimToken):null;
  const workspaces=user?await listBrowserWorkspaces(user.id):[];
  const selected=workspaces.find(w=>w.organization_id===jar.get(BROWSER_WORKSPACE_COOKIE)?.value);
  const history=selected&&user?await browserScanHistory(selected.organization_id,user.id):[];
  const active=selected?.status==="active"&&(!selected.expires_at||new Date(selected.expires_at).getTime()>Date.now());
  const remaining=Math.max(0,BROWSER_MONTHLY_LIMIT-(selected?.used??0));
  return <BrowserShell><section className="border-b border-sky-100 bg-gradient-to-br from-sky-50 via-white to-emerald-50"><div className="mx-auto grid max-w-6xl gap-10 px-6 py-14 lg:grid-cols-[1.3fr_1fr] lg:items-center">
    <div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-sky-800">AWS Marketplace · Free website scanner</p><h1 className="mt-5 text-4xl font-semibold leading-tight tracking-tight sm:text-5xl">Your website.<br/><span className="text-sky-700">The evidence behind it.</span></h1><p className="mt-5 max-w-xl text-lg leading-8 text-slate-600">Enter a public URL. Review observed data collection, services loaded by the website, and privacy signals that deserve a closer look.</p><a href="#access" className="mt-6 inline-block rounded-xl bg-sky-800 px-6 py-3 font-semibold text-white">{selected?"Go to my workspace":"Set up free access"} →</a></div>
    <div className={`${panel} shadow-sm`}><p className="text-4xl font-semibold">$0<span className="ml-2 text-base font-normal text-slate-500">Free access</span></p><ul className="mt-6 space-y-4 text-sm leading-6 text-slate-600"><li><strong className="text-slate-900">50 single-page scans</strong> each UTC calendar month</li><li>Evidence-backed browser reports and scan history</li><li>Cookies, trackers, consent controls and policy disclosures, where evidence is available</li><li>No MCP client or API-key configuration</li></ul><p className="mt-5 border-t pt-4 text-xs leading-5 text-slate-500">No overage charges or automatic paid conversion. Unused scans do not roll over. Safety checks and cooldowns apply.</p></div>
  </div></section><div className="mx-auto max-w-6xl space-y-7 px-6 py-10">
    <ol aria-label="Getting started" className="grid grid-cols-3 gap-3 text-sm font-semibold text-slate-600">{["1. Link your account","2. Enter a website","3. Review your report"].map(t=><li key={t} className="rounded-xl bg-white p-4">{t}</li>)}</ol>
    <section id="access" className={panel}><div className="flex flex-wrap justify-between gap-3"><h2 className="text-2xl font-semibold">Your account &amp; subscription</h2>{user&&<p className="break-all text-sm text-slate-500">{user.email}</p>}</div>
      {!enabled?<p className="mt-4 leading-7 text-slate-600">This offering is being prepared for Limited testing. Account activation is not available yet. Contact <a className={link} href="mailto:support@certscore.ai">support@certscore.ai</a> for help.</p>:<>
      {!user&&<div className="mt-5 space-y-4"><p className="text-slate-600">{claim?"Your AWS handoff is ready. Sign in or create an account to link your subscription.":"Subscribe in AWS Marketplace and choose Set up your account. You can use your existing CertScore account."}</p><Link className={link} href="/login?next=%2Fmarketplace%2Fbrowser">Sign in or create an account →</Link></div>}
      {user&&claim&&<div className="mt-5 rounded-xl border border-sky-200 bg-sky-50 p-5"><h3 className="font-semibold">Confirm your subscription</h3><p className="my-3 text-sm leading-6">Link AWS account ending <strong>{claim.buyer_account_id.slice(-4)}</strong> to <strong>{user.email}</strong>. We will select a separate Marketplace workspace. Your existing CertScore membership and paid plan stay intact. Re-subscription reuses its earlier workspace and remaining allowance.</p><BrowserAction operation="claim" label="Confirm and link subscription"/></div>}
      {user&&!claim&&workspaces.length===0&&<p className="mt-4 leading-7 text-slate-600">In AWS Marketplace, open this product and choose <strong>Set up your account</strong>. If a previous setup link expired, start there again.</p>}
      <div className="mt-6 space-y-4">{workspaces.map(w=>{const usable=w.status==="active"&&(!w.expires_at||new Date(w.expires_at).getTime()>Date.now());return <article key={w.organization_id} className={`rounded-xl border p-5 ${selected?.organization_id===w.organization_id?"border-sky-300 bg-sky-50/40":"border-slate-200"}`}>
        <div className="flex flex-wrap justify-between gap-3"><h3 className="font-semibold">{w.name} · AWS …{w.buyer_account_id.slice(-4)}</h3><span className={`rounded-full px-3 py-1 text-xs font-semibold ${usable?"bg-emerald-100 text-emerald-900":"bg-amber-100 text-amber-900"}`}>{usable?"Active":w.status==="pending"?"Activation pending":"Inactive or verification required"}</span></div>
        <p className="mt-3 text-sm text-slate-600">{w.used} of 50 scan credits used or reserved this month · {Math.max(0,50-w.used)} remaining</p><p className="mt-2 text-xs text-slate-500">{w.expires_at?`Access ends ${date(w.expires_at)} (UTC).`:"No end date reported by AWS."} {w.verified_at?`Last verified ${date(w.verified_at)}. Access is checked again before scanning.`:"Awaiting AWS verification."}</p>
        <div className="mt-4 flex flex-wrap gap-3"><BrowserAction operation="select" organizationId={w.organization_id} label={selected?.organization_id===w.organization_id?"Workspace selected":"Use this workspace"}/><BrowserAction operation="refresh" organizationId={w.organization_id} label="Check subscription"/>{!w.welcome_sent_at&&<BrowserAction operation="welcome" organizationId={w.organization_id} label="Email setup instructions"/>}</div>
        <details className="mt-3 text-xs text-slate-500"><summary className="cursor-pointer py-2">Subscription details for support</summary><p className="break-all">{w.license_arn??"Activation pending"}</p><p>Workspace: {w.organization_id}</p></details>
      </article>})}</div>{user&&workspaces.length>0&&<div className="mt-5 flex flex-wrap items-start gap-5"><BrowserAction operation="leave" label="Return to my ordinary workspace"/><a className={link} href="https://console.aws.amazon.com/marketplace/home#/subscriptions">Manage AWS subscriptions ↗</a></div>}
      </>}
    </section>
    <div className="grid items-start gap-7 lg:grid-cols-2"><section className={panel}><p className="text-xs font-semibold uppercase tracking-wider text-sky-700">Start a review</p><h2 className="mb-5 mt-2 text-2xl font-semibold">What website is on your mind?</h2><BrowserScanForm organizationId={selected?.organization_id} requestId={randomUUID()} disabled={!enabled||!active}/>{!active&&<p className="mt-4 text-sm leading-6 text-slate-500">Select a workspace with a verified active subscription to start scanning.</p>}{active&&<p className="mt-4 text-sm text-slate-500">{remaining} fresh scan credits remaining. Recent report reuse uses no credit.</p>}</section>
    <section className={panel}><h2 className="text-2xl font-semibold">Your recent reports</h2><p className="mt-3 text-sm leading-6 text-slate-500">Open a scan to follow its progress and review its report when ready.</p>{history.length===0?<p className="mt-7 rounded-xl bg-slate-50 p-5 text-sm text-slate-600">Your new scans will appear here.</p>:<ul className="mt-5 divide-y divide-slate-100">{history.map(s=><li key={s.id} className="py-4"><Link className={`${link} break-all`} href={`/app/scans/${s.id}`}>{s.normalized_url}</Link><p className="mt-1 text-xs text-slate-500">{s.status} · {date(s.created_at)}{s.refunded_at?" · credit returned":""}</p></li>)}</ul>}</section></div>
    <section className={panel}><h2 className="text-xl font-semibold">Clear limits. Help when you need it.</h2><div className="mt-4 grid gap-6 text-sm leading-7 text-slate-600 md:grid-cols-2"><p>A scan covers one submitted public URL, with linked policy evidence where available. Full-site crawling, scheduled monitoring and additional API/MCP access are not included. Results describe observations and inspection limitations, not legal conclusions.</p><p>For activation, account linking, scan results, cancellation or refund questions, email <a className={link} href="mailto:support@certscore.ai">support@certscore.ai</a>. This offer has no software purchase fees. Cancel through AWS Marketplace to stop new scans; re-subscribing does not reset this month’s credits. Existing reports follow the applicable access and retention policies.</p></div></section>
  </div></BrowserShell>;
}
